CarID   NUMBER(5),
    CarName VARCHAR2(100),
    ModelID NUMBER(5),
    MakerID NUMBER(5),
--
INSERT INTO CARS.CAR_NAMES(CarID, ModelID, MakerID, CarName) 
--
--
MODELID    MAKERID MAKERNAME     MODELSHORTDESC    MODELLONGDESC
__________ __________ _____________ _________________ _________________________________________
         1          1 AMC           AMC               American Motors Corporation
         2          2 VOLKSWAGEN    AUDI              Audi
         3          3 BMW           BMW               Bayerische Motoren Werke
         4          4 GM            BUICK             Buick Motor Division of General Motors
         5          4 GM            CADILLAC          Cadillac Division of General Motors
         6          5 FORD          CAPRI             Mercury Division of Ford Motor Company
         7          4 GM            CHEVROLET         Chevrolet Division of General Motors
         8          6 CHRYSLER      CHRYSLER          Chrysler Corporation
         9          7 CITROEN       CITROEN           Citroen Automobiles
        10          8 NISSAN        DATSON            Datsun Division of Nissan Motors
        11          6 CHRYSLER      DODGE             Dodge Division of Chrysler Corporation
        12          9 FIAT          FIAT              Fiat Automobiles
        13          5 FORD          FORD              Ford Motor Company
        15         11 HONDA         HONDA             Honda Motor Company

   MODELID    MAKERID MAKERNAME       MODELSHORTDESC    MODELLONGDESC
__________ __________ _______________ _________________ ____________________________________________
        16         12 MAZDA           MAZDA             Mazda Motor Corporation
        17         13 DAIMLER BENZ    MERCEDES          Mercedes-Benz Division of Daimler AG
        18         13 DAIMLER BENZ    MERCEDES-BENZ     Mercedes-Benz Division of Daimler AG
        19          5 FORD            MERCURY           Mercury Division of Ford Motor Company
        20          8 NISSAN          NISSAN            Nissan Motors
        21          4 GM              OLDSMOBILE        Oldsmobile Division of General Motors
        22         14 OPEL            OPEL              Opel Division of General Motors
        23         15 PEUGEAUT        PEUGEOT           Peugeot Automobiles
        24          6 CHRYSLER        PLYMOUTH          Plymouth Division of Chrysler Corporation
        25          4 GM              PONTIAC           Pontiac Division of General Motors
        26         16 RENAULT         RENAULT           Renault Automobiles
        27         17 SAAB            SAAB              Saab Automobile
        28         18 SUBARU          SUBARU            Subaru Corporation
        29         19 TOYOTA          TOYOTA            Toyota Motor Corporation

   MODELID    MAKERID MAKERNAME     MODELSHORTDESC    MODELLONGDESC
__________ __________ _____________ _________________ _____________________________________________
        30         20 TRIUMPH       TRIUMPH           Triumph Motor Company
        31          2 VOLKSWAGEN    VOLKSWAGEN        Volkswagen Automobiles
        32         21 VOLVO         VOLVO             Volvo Cars
        33         22 KIA           KIA               Kia Motors Corporation
        34         23 HYUNDAI       HYUNDAI           Hyundai Motor Company
        35          6 CHRYSLER      JEEP              Jeep Division of Chrysler Corporation
        36         19 TOYOTA        SCION             Scion Division of Toyota Motor Corporation
--
INSERT INTO CAR_NAMES VALUES(1,'CHEVROLET CHEVELLE MALIBU', 7,4);

INSERT INTO CAR_NAMES VALUES(2,'BUICK SKYLARK 320', 4,4);

INSERT INTO CAR_NAMES VALUES(3,'PLYMOUTH SATELLITE', 24,6);

INSERT INTO CAR_NAMES VALUES(4,'AMC REBEL SST',1,1);

INSERT INTO CAR_NAMES VALUES(5,'FORD TORINO', 13,5);

INSERT INTO CAR_NAMES VALUES(6,'FORD GALAXIE 500',13,5);

INSERT INTO CAR_NAMES VALUES(7,'CHEVROLET IMPALA',7,4);

INSERT INTO CAR_NAMES VALUES(8,'PLYMOUTH FURY III',24,6);

INSERT INTO CAR_NAMES VALUES(9,'PONTIAC CATALINA',25,4);

INSERT INTO CAR_NAMES VALUES(10,'AMC AMBASSADOR DPL',1,1);

INSERT INTO CAR_NAMES VALUES(11,'CITROEN DS-21 PALLAS',9,7);

INSERT INTO CAR_NAMES VALUES(12,'CHEVROLET CHEVELLE CONCOURS (SW)',7,4);

INSERT INTO CAR_NAMES VALUES(13,'FORD TORINO (SW)',13,5);

INSERT INTO CAR_NAMES VALUES(14,'PLYMOUTH SATELLITE (SW)',24,6);

INSERT INTO CAR_NAMES VALUES(15,'AMC REBEL SST (SW)',1,1);

INSERT INTO CAR_NAMES VALUES(16,'DODGE CHALLENGER SE',11,6);

INSERT INTO CAR_NAMES VALUES(17,'PLYMOUTH CUDA 340',24,6);

INSERT INTO CAR_NAMES VALUES(18,'FORD MUSTANG BOSS 302',13,5);

INSERT INTO CAR_NAMES VALUES(19,'CHEVROLET MONTE CARLO',7,4);

INSERT INTO CAR_NAMES VALUES(20,'BUICK ESTATE WAGON (SW)',4,4);

INSERT INTO CAR_NAMES VALUES(21,'TOYOTA CORONA MARK II', 29,19);

INSERT INTO CAR_NAMES VALUES(22,'PLYMOUTH DUSTER', 24,6);

INSERT INTO CAR_NAMES VALUES(23,'AMC HORNET', 1,1);

INSERT INTO CAR_NAMES VALUES(24,'FORD MAVERICK', 13,5);

INSERT INTO CAR_NAMES VALUES(25,'DATSUN PL510', 10,8);

INSERT INTO CAR_NAMES VALUES(26,'VOLKSWAGEN 1131 DELUXE SEDAN', 31,2);

INSERT INTO CAR_NAMES VALUES(27,'PEUGEOT 504', 23,15);

INSERT INTO CAR_NAMES VALUES(28,'AUDI 100 LS', 2,2);

INSERT INTO CAR_NAMES VALUES(29,'SAAB 99E', 27,17);

INSERT INTO CAR_NAMES VALUES(30,'BMW 2002', 3,3);

INSERT INTO CAR_NAMES VALUES(31,'AMC GREMLIN', 1,1);

INSERT INTO CAR_NAMES VALUES(32,'FORD F250', 13,5);

INSERT INTO CAR_NAMES VALUES(33,'CHEVY C20', 7,4);

INSERT INTO CAR_NAMES VALUES(34,'DODGE D200', 11,6);

INSERT INTO CAR_NAMES VALUES(35,'HI 1200D', 12,9);

INSERT INTO CAR_NAMES VALUES(36,'DATSUN PL510', 10,8);

INSERT INTO CAR_NAMES VALUES(37,'CHEVROLET VEGA 2300', 7,4);

INSERT INTO CAR_NAMES VALUES(38,'TOYOTA CORONA', 29, 19);

INSERT INTO CAR_NAMES VALUES(39,'FORD PINTO', 13, 5);

INSERT INTO CAR_NAMES VALUES(40,'VOLKSWAGEN SUPER BEETLE 117', 31, 2);

INSERT INTO CAR_NAMES VALUES(41,'AMC GREMLIN', 1, 1);

INSERT INTO CAR_NAMES VALUES(42,'PLYMOUTH SATELLITE CUSTOM', 24, 6);

INSERT INTO CAR_NAMES VALUES(43,'CHEVROLET CHEVELLE MALIBU', 7, 4);

INSERT INTO CAR_NAMES VALUES(44,'FORD TORINO 500', 13, 5);

INSERT INTO CAR_NAMES VALUES(45,'AMC MATADOR', 1, 1);

INSERT INTO CAR_NAMES VALUES(46,'CHEVROLET IMPALA', 7, 4);

INSERT INTO CAR_NAMES VALUES(47,'PONTIAC CATALINA BROUGHAM', 25, 4);

INSERT INTO CAR_NAMES VALUES(48,'FORD GALAXIE 500', 13, 5);

INSERT INTO CAR_NAMES VALUES(49,'PLYMOUTH FURY III', 24, 6);

INSERT INTO CAR_NAMES VALUES(50,'DODGE MONACO (SW)', 11, 6);

INSERT INTO CAR_NAMES VALUES(51,'FORD COUNTRY SQUIRE (SW)', 13, 5);

INSERT INTO CAR_NAMES VALUES(52,'PONTIAC SAFARI (SW)', 25, 4);

INSERT INTO CAR_NAMES VALUES(53,'AMC HORNET SPORTABOUT (SW)', 1, 1);

INSERT INTO CAR_NAMES VALUES(54,'CHEVROLET VEGA (SW)', 7, 4);

INSERT INTO CAR_NAMES VALUES(55,'PONTIAC FIREBIRD', 25, 4);

INSERT INTO CAR_NAMES VALUES(56,'FORD MUSTANG', 13, 5);

INSERT INTO CAR_NAMES VALUES(57,'MERCURY CAPRI 2000', 19, 5);

INSERT INTO CAR_NAMES VALUES(58,'OPEL 1900', 22, 14);

INSERT INTO CAR_NAMES VALUES(59,'PEUGEOT 304', 23, 15);

INSERT INTO CAR_NAMES VALUES(60,'FIAT 124B', 12, 9);

INSERT INTO CAR_NAMES VALUES(61,'TOYOTA COROLLA 1200', 29, 19);

INSERT INTO CAR_NAMES VALUES(62,'DATSUN 1200', 10, 8);

INSERT INTO CAR_NAMES VALUES(63,'VOLKSWAGEN MODEL 111', 31, 2);

INSERT INTO CAR_NAMES VALUES(64,'PLYMOUTH CRICKET', 24, 6);

INSERT INTO CAR_NAMES VALUES(65,'TOYOTA CORONA HARDTOP', 29, 19);

INSERT INTO CAR_NAMES VALUES(66,'DODGE COLT HARDTOP', 11, 6);

INSERT INTO CAR_NAMES VALUES(67,'VOLKSWAGEN TYPE 3', 31, 2);

INSERT INTO CAR_NAMES VALUES(68,'CHEVROLET VEGA', 7, 4);

INSERT INTO CAR_NAMES VALUES(69,'FORD PINTO RUNABOUT', 13, 5);

INSERT INTO CAR_NAMES VALUES(70,'CHEVROLET IMPALA', 7, 4);    

INSERT INTO CAR_NAMES VALUES(71,'PONTIAC CATALINA', 25, 4);   

INSERT INTO CAR_NAMES VALUES(72,'PLYMOUTH FURY III', 24, 6);

INSERT INTO CAR_NAMES VALUES(73,'FORD GALAXIE 500', 13, 5);

INSERT INTO CAR_NAMES VALUES(74,'AMC AMBASSADOR SST', 1, 1);

INSERT INTO CAR_NAMES VALUES(75,'MERCURY MARQUIS', 19, 5);

INSERT INTO CAR_NAMES VALUES(76,'BUICK LESABRE CUSTOM', 4, 4);

INSERT INTO CAR_NAMES VALUES(77,'OLDSMOBILE DELTA 88 ROYALE', 21, 4);

INSERT INTO CAR_NAMES VALUES(78,'CHRYSLER NEWPORT ROYAL', 8, 6);

INSERT INTO CAR_NAMES VALUES(79,'MAZDA RX2 COUPE', 16, 12);

INSERT INTO CAR_NAMES VALUES(80,'AMC MATADOR (SW)', 1, 1);

INSERT INTO CAR_NAMES VALUES(81,'CHEVROLET CHEVELLE CONCOURS (SW)', 7, 4);

INSERT INTO CAR_NAMES VALUES(82,'FORD GRAN TORINO (SW)', 13, 5);

INSERT INTO CAR_NAMES VALUES(83,'PLYMOUTH SATELLITE CUSTOM (SW)', 24, 6);

INSERT INTO CAR_NAMES VALUES(84,'VOLVO 145E (SW)', 32, 21);

INSERT INTO CAR_NAMES VALUES(85,'VOLKSWAGEN 411 (SW)', 31, 2);

INSERT INTO CAR_NAMES VALUES(86,'PEUGEOT 504 (SW)', 23, 15);

INSERT INTO CAR_NAMES VALUES(87,'RENAULT 12 (SW)', 26, 16);

INSERT INTO CAR_NAMES VALUES(88,'FORD PINTO (SW)', 13, 5);

INSERT INTO CAR_NAMES VALUES(89,'DATSUN 510 (SW)', 10, 8);

INSERT INTO CAR_NAMES VALUES(90,'TOYOTA CORONA MARK II (SW)', 29, 19);

INSERT INTO CAR_NAMES VALUES(91,'DODGE COLT (SW)', 11, 6);

INSERT INTO CAR_NAMES VALUES(92,'TOYOTA COROLLA 1600 (SW)', 29, 19);

INSERT INTO CAR_NAMES VALUES(93,'BUICK CENTURY 350', 4, 4);

INSERT INTO CAR_NAMES VALUES(94,'AMC MATADOR', 1, 1);

INSERT INTO CAR_NAMES VALUES(95,'CHEVROLET MALIBU', 7, 4);

INSERT INTO CAR_NAMES VALUES(96,'FORD GRAN TORINO', 13, 5);

INSERT INTO CAR_NAMES VALUES(97,'DODGE CORONET CUSTOM', 11, 6);

INSERT INTO CAR_NAMES VALUES(98,'MERCURY MARQUIS BROUGHAM', 19, 5);

INSERT INTO CAR_NAMES VALUES(99,'CHEVROLET CAPRICE CLASSIC', 7, 4);

INSERT INTO CAR_NAMES VALUES(100,'FORD LTD', 13, 5);

INSERT INTO CAR_NAMES VALUES(101,'PLYMOUTH FURY GRAN SEDAN', 24, 6);

INSERT INTO CAR_NAMES VALUES(102,'CHRYSLER NEW YORKER BROUGHAM', 8, 6);

INSERT INTO CAR_NAMES VALUES(103,'BUICK ELECTRA 225 CUSTOM', 4, 4);

INSERT INTO CAR_NAMES VALUES(104,'AMC AMBASSADOR BROUGHAM', 1, 1);

INSERT INTO CAR_NAMES VALUES(105,'PLYMOUTH VALIANT', 24, 6);

INSERT INTO CAR_NAMES VALUES(106,'CHEVROLET NOVA CUSTOM', 7, 4);

INSERT INTO CAR_NAMES VALUES(107,'AMC HORNET', 1, 1);

INSERT INTO CAR_NAMES VALUES(108,'FORD MAVERICK', 13, 5);

INSERT INTO CAR_NAMES VALUES(109,'PLYMOUTH DUSTER', 24, 6);

INSERT INTO CAR_NAMES VALUES(110,'VOLKSWAGEN SUPER BEETLE', 31, 2);

INSERT INTO CAR_NAMES VALUES(111,'CHEVROLET IMPALA', 7, 4);

INSERT INTO CAR_NAMES VALUES(112,'FORD COUNTRY', 13, 5);

INSERT INTO CAR_NAMES VALUES(113,'PLYMOUTH CUSTOM SUBURB', 24, 6);

INSERT INTO CAR_NAMES VALUES(114,'OLDSMOBILE VISTA CRUISER', 21, 4);

INSERT INTO CAR_NAMES VALUES(115,'AMC GREMLIN', 1, 1);

INSERT INTO CAR_NAMES VALUES(116,'TOYOTA CARINA', 29, 19);

INSERT INTO CAR_NAMES VALUES(117,'CHEVROLET VEGA', 7, 4);

INSERT INTO CAR_NAMES VALUES(118,'DATSUN 610', 10, 8);

INSERT INTO CAR_NAMES VALUES(119,'MAZDA RX3', 16, 12);

INSERT INTO CAR_NAMES VALUES(120,'FORD PINTO', 13, 5);

INSERT INTO CAR_NAMES VALUES(121,'MERCURY CAPRI V6', 19, 5);

INSERT INTO CAR_NAMES VALUES(122,'FIAT 124 SPORT COUPE', 12, 9);

INSERT INTO CAR_NAMES VALUES(123,'CHEVROLET MONTE CARLO S', 7, 4);

INSERT INTO CAR_NAMES VALUES(124,'PONTIAC GRAND PRIX', 25, 4);

INSERT INTO CAR_NAMES VALUES(125,'FIAT 128', 12, 9);

INSERT INTO CAR_NAMES VALUES(126,'OPEL MANTA', 22, 14);

INSERT INTO CAR_NAMES VALUES(127,'AUDI 100LS', 2, 2);

INSERT INTO CAR_NAMES VALUES(128,'VOLVO 144EA', 32, 21);

INSERT INTO CAR_NAMES VALUES(129,'DODGE DART CUSTOM', 11, 6);

INSERT INTO CAR_NAMES VALUES(130,'SAAB 99LE', 27, 17);

INSERT INTO CAR_NAMES VALUES(131,'TOYOTA MARK II', 29, 19);

INSERT INTO CAR_NAMES VALUES(132,'OLDSMOBILE OMEGA', 21, 4);

INSERT INTO CAR_NAMES VALUES(133,'PLYMOUTH DUSTER', 24, 6);

INSERT INTO CAR_NAMES VALUES(134,'FORD MAVERICK', 13, 5);

INSERT INTO CAR_NAMES VALUES(135,'AMC HORNET', 1, 1);

INSERT INTO CAR_NAMES VALUES(136,'CHEVROLET NOVA', 7, 4);

INSERT INTO CAR_NAMES VALUES(137,'DATSUN B210', 10, 8);

INSERT INTO CAR_NAMES VALUES(138,'FORD PINTO', 13, 5);

INSERT INTO CAR_NAMES VALUES(139,'TOYOTA COROLLA 1200', 29, 19);

INSERT INTO CAR_NAMES VALUES(140,'CHEVROLET VEGA',  7, 4);

INSERT INTO CAR_NAMES VALUES(141,'CHEVROLET CHEVROLET MALIBU CLASSIC', 7, 4);

INSERT INTO CAR_NAMES VALUES(142,'AMC MATADOR',   1, 1);

INSERT INTO CAR_NAMES VALUES(143,'PLYMOUTH SATELLITE SEBRING', 24, 6);

INSERT INTO CAR_NAMES VALUES(144,'FORD GRAN TORINO', 13, 5);

INSERT INTO CAR_NAMES VALUES(145,'BUICK CENTURY LUXUS (SW)', 4, 4);

INSERT INTO CAR_NAMES VALUES(146,'DODGE CORONET CUSTOM (SW)', 11, 6);

INSERT INTO CAR_NAMES VALUES(147,'FORD GRAN TORINO (SW)', 13, 5);

INSERT INTO CAR_NAMES VALUES(148,'AMC MATADOR (SW)', 1, 1);

INSERT INTO CAR_NAMES VALUES(149,'AUDI FOX', 2, 2);

INSERT INTO CAR_NAMES VALUES(150,'VOLKSWAGEN DASHER', 31, 2);

INSERT INTO CAR_NAMES VALUES(151,'OPEL MANTA', 22, 14);

INSERT INTO CAR_NAMES VALUES(152,'TOYOTA CORONA', 29, 19);

INSERT INTO CAR_NAMES VALUES(153,'DATSUN 710', 10, 8);

INSERT INTO CAR_NAMES VALUES(154,'DODGE COLT', 11, 6);

INSERT INTO CAR_NAMES VALUES(155,'FIAT 128', 12, 9);

INSERT INTO CAR_NAMES VALUES(156,'FIAT 124 TC', 12, 9);

INSERT INTO CAR_NAMES VALUES(157,'HONDA CIVIC', 15, 11);

INSERT INTO CAR_NAMES VALUES(158,'SUBARU', 28, 18);

INSERT INTO CAR_NAMES VALUES(159,'FIAT X1.9', 12, 9);

INSERT INTO CAR_NAMES VALUES(160,'PLYMOUTH VALIANT CUSTOM', 24, 6);

INSERT INTO CAR_NAMES VALUES(161,'CHEVROLET NOVA', 7, 4);

INSERT INTO CAR_NAMES VALUES(162,'MERCURY MONARCH', 19, 5);

INSERT INTO CAR_NAMES VALUES(163,'FORD MAVERICK', 13, 5);

INSERT INTO CAR_NAMES VALUES(164,'PONTIAC CATALINA', 25, 4);

INSERT INTO CAR_NAMES VALUES(165,'CHEVROLET BEL AIR', 7, 4);

INSERT INTO CAR_NAMES VALUES(166,'PLYMOUTH GRAND FURY', 24, 6);

INSERT INTO CAR_NAMES VALUES(167,'FORD LTD', 13, 5);

INSERT INTO CAR_NAMES VALUES(168,'BUICK CENTURY', 4, 4);

INSERT INTO CAR_NAMES VALUES(169,'CHEVROLET CHEVELLE MALIBU', 7, 4);

INSERT INTO CAR_NAMES VALUES(170,'AMC MATADOR', 1, 1);

INSERT INTO CAR_NAMES VALUES(171,'PLYMOUTH FURY', 24, 6);

INSERT INTO CAR_NAMES VALUES(172,'BUICK SKYHAWK', 4, 4);

INSERT INTO CAR_NAMES VALUES(173,'CHEVROLET CHEVETTE', 7, 4);

INSERT INTO CAR_NAMES VALUES(174,'FORD MUSTANG II', 13, 5);

INSERT INTO CAR_NAMES VALUES(175,'TOYOTA COROLLA', 29, 19);

INSERT INTO CAR_NAMES VALUES(176,'FORD PINTO', 13, 5);

INSERT INTO CAR_NAMES VALUES(177,'AMC GREMLIN', 1, 1);

INSERT INTO CAR_NAMES VALUES(178,'PONTIAC ASTRO', 25, 4);

INSERT INTO CAR_NAMES VALUES(179,'TOYOTA CORONA', 29, 19);

INSERT INTO CAR_NAMES VALUES(180,'VOLKSWAGEN DASHER', 31, 2);

INSERT INTO CAR_NAMES VALUES(181, 'DATSUN 710', 10, 8);

INSERT INTO CAR_NAMES VALUES(182,'FORD PINTO', 13, 5);

INSERT INTO CAR_NAMES VALUES(183,'VOLKSWAGEN RABBIT', 31, 2);

INSERT INTO CAR_NAMES VALUES(184,'AMC PACER', 1, 1);

INSERT INTO CAR_NAMES VALUES(185,'AUDI 100LS', 2, 2);

INSERT INTO CAR_NAMES VALUES(186,'PEUGEOT 504', 23, 15);

INSERT INTO CAR_NAMES VALUES(187,'VOLVO 244DL', 32, 21);

INSERT INTO CAR_NAMES VALUES(188,'SAAB 99LE', 27, 17);

INSERT INTO CAR_NAMES VALUES(189,'HONDA CIVIC CVCC', 15, 11);

INSERT INTO CAR_NAMES VALUES(190,'FIAT 131', 12, 9);

INSERT INTO CAR_NAMES VALUES(191,'OPEL 1900', 22, 14);

INSERT INTO CAR_NAMES VALUES(192,'CAPRI II', 6, 5);

INSERT INTO CAR_NAMES VALUES(193,'DODGE COLT', 11, 6);

INSERT INTO CAR_NAMES VALUES(194,'RENAULT 12TL', 26, 16);

INSERT INTO CAR_NAMES VALUES(195,'CHEVROLET CHEVELLE MALIBU CLASSIC', 7, 4);

INSERT INTO CAR_NAMES VALUES(196,'DODGE CORONET BROUGHAM', 11, 6);

INSERT INTO CAR_NAMES VALUES(197,'AMC MATADOR', 1, 1);

INSERT INTO CAR_NAMES VALUES(198,'FORD GRAN TORINO', 13, 5);

INSERT INTO CAR_NAMES VALUES(199,'PLYMOUTH VALIANT', 24, 6);

INSERT INTO CAR_NAMES VALUES(200, 'CHEVROLET NOVA', 7, 4);

INSERT INTO CAR_NAMES VALUES(201,'FORD MAVERICK', 13, 5);

INSERT INTO CAR_NAMES VALUES(202,'AMC HORNET', 1, 1);

INSERT INTO CAR_NAMES VALUES(203,'CHEVROLET CHEVETTE', 7, 4);

INSERT INTO CAR_NAMES VALUES(204, 'CHEVROLET WOODY', 7, 4);

INSERT INTO CAR_NAMES VALUES(205,'VW RABBIT', 31, 2);

INSERT INTO CAR_NAMES VALUES(206,'HONDA CIVIC', 15, 11);

INSERT INTO CAR_NAMES VALUES(207,'DODGE ASPEN SE', 11, 6);

INSERT INTO CAR_NAMES VALUES(208,'FORD GRANADA GHIA', 13, 5);

INSERT INTO CAR_NAMES VALUES(209,'PONTIAC VENTURA SJ', 25, 4);

INSERT INTO CAR_NAMES VALUES(210,'AMC PACER D/L', 1, 1);

INSERT INTO CAR_NAMES VALUES(211,'VOLKSWAGEN RABBIT', 31, 2);

INSERT INTO CAR_NAMES VALUES(212,'DATSUN B-210', 10, 8);

INSERT INTO CAR_NAMES VALUES(213,'TOYOTA COROLLA',  29, 19);

INSERT INTO CAR_NAMES VALUES(214,'FORD PINTO', 13, 5);

INSERT INTO CAR_NAMES VALUES(215,'VOLVO 245', 32, 21);

INSERT INTO CAR_NAMES VALUES(216,'PLYMOUTH VOLARE PREMIER V8', 24, 6);

INSERT INTO CAR_NAMES VALUES(217,'PEUGEOT 504', 23, 15);

INSERT INTO CAR_NAMES VALUES(218,'TOYOTA MARK II', 29, 19);

INSERT INTO CAR_NAMES VALUES(219,'MERCEDES-BENZ 280S', 17, 13);

INSERT INTO CAR_NAMES VALUES(220,'CADILLAC SEVILLE', 5, 4);

INSERT INTO CAR_NAMES VALUES(221,'CHEVY C10', 7, 4);

INSERT INTO CAR_NAMES VALUES(222,'FORD F108', 13, 5);

INSERT INTO CAR_NAMES VALUES(223,'DODGE D100', 11, 6);

INSERT INTO CAR_NAMES VALUES(224,'HONDA ACCORD CVCC', 15, 11);

INSERT INTO CAR_NAMES VALUES(225,'BUICK OPEL ISUZU DELUXE', 4, 4);

INSERT INTO CAR_NAMES VALUES(226,'RENAULT 5 GTL', 26, 16);

INSERT INTO CAR_NAMES VALUES(227,'PLYMOUTH ARROW GS', 24, 6);

INSERT INTO CAR_NAMES VALUES(228,'DATSUN F-10 HATCHBACK', 10, 8);

INSERT INTO CAR_NAMES VALUES(229,'CHEVROLET CAPRICE CLASSIC', 7, 4);

INSERT INTO CAR_NAMES VALUES(230,'OLDSMOBILE CUTLASS SUPREME', 21, 4);

INSERT INTO CAR_NAMES VALUES(231,'DODGE MONACO BROUGHAM', 11, 6);

INSERT INTO CAR_NAMES VALUES(232,'MERCURY COUGAR BROUGHAM', 19, 5);

INSERT INTO CAR_NAMES VALUES(233,'CHEVROLET CONCOURS', 7, 4);

INSERT INTO CAR_NAMES VALUES(234,'BUICK SKYLARK',   4, 4);

INSERT INTO CAR_NAMES VALUES(235,'PLYMOUTH VOLARE CUSTOM', 24, 6);

INSERT INTO CAR_NAMES VALUES(236,'FORD GRANADA', 13, 5);

INSERT INTO CAR_NAMES VALUES(237,'PONTIAC GRAND PRIX LJ', 25, 4);

INSERT INTO CAR_NAMES VALUES(238,'CHEVROLET MONTE CARLO LANDAU', 7, 4);

INSERT INTO CAR_NAMES VALUES(239,'CHRYSLER CORDOBA', 8, 6);

INSERT INTO CAR_NAMES VALUES(240,'FORD THUNDERBIRD', 13, 5);

INSERT INTO CAR_NAMES VALUES(241,'VOLKSWAGEN RABBIT CUSTOM', 31, 2);

INSERT INTO CAR_NAMES VALUES(242,'PONTIAC SUNBIRD COUPE', 25, 4);

INSERT INTO CAR_NAMES VALUES(243,'TOYOTA COROLLA LIFTBACK', 29, 19);

INSERT INTO CAR_NAMES VALUES(244,'FORD MUSTANG II 2+2', 13, 5);

INSERT INTO CAR_NAMES VALUES(245,'CHEVROLET CHEVETTE', 7, 4);

INSERT INTO CAR_NAMES VALUES(246,'DODGE COLT M/M', 11, 6);

INSERT INTO CAR_NAMES VALUES(247,'SUBARU DL', 28, 18);

INSERT INTO CAR_NAMES VALUES(248,'VOLKSWAGEN DASHER', 31, 2);

INSERT INTO CAR_NAMES VALUES(249,'DATSUN 810', 10, 8);

INSERT INTO CAR_NAMES VALUES(250, 'BMW 320I', 3, 3);

INSERT INTO CAR_NAMES VALUES(251,'MAZDA RX-4', 16, 12);

INSERT INTO CAR_NAMES VALUES(252,'VOLKSWAGEN RABBIT CUSTOM DIESEL', 31, 2);

INSERT INTO CAR_NAMES VALUES(253,'FORD FIESTA', 13, 5);

INSERT INTO CAR_NAMES VALUES(254,'MAZDA GLC DELUXE', 16, 12);

INSERT INTO CAR_NAMES VALUES(255,'DATSUN B210 GX', 10, 8);

INSERT INTO CAR_NAMES VALUES(256,'HONDA CIVIC CVCC', 15, 11);

INSERT INTO CAR_NAMES VALUES(257,'OLDSMOBILE CUTLASS SALON BROUGHAM', 21, 4);

INSERT INTO CAR_NAMES VALUES(258,'DODGE DIPLOMAT', 11, 6);

INSERT INTO CAR_NAMES VALUES(259,'MERCURY MONARCH GHIA', 19, 5);

INSERT INTO CAR_NAMES VALUES(260,'PONTIAC PHOENIX LJ', 25, 4);

INSERT INTO CAR_NAMES VALUES(261,'CHEVROLET MALIBU', 7, 4);

INSERT INTO CAR_NAMES VALUES(262,'FORD FAIRMONT (AUTO)', 13, 5);

INSERT INTO CAR_NAMES VALUES(263,'FORD FAIRMONT (MAN)', 13, 5);

INSERT INTO CAR_NAMES VALUES(264,'PLYMOUTH VOLARE',  24, 6);

INSERT INTO CAR_NAMES VALUES(265,'AMC CONCORD', 1, 1);

INSERT INTO CAR_NAMES VALUES(266,'BUICK CENTURY SPECIAL', 4, 4);

INSERT INTO CAR_NAMES VALUES(267,'MERCURY ZEPHYR', 19, 5);

INSERT INTO CAR_NAMES VALUES(268,'DODGE ASPEN', 11, 6);

INSERT INTO CAR_NAMES VALUES(269,'AMC CONCORD D/L', 1, 1);

INSERT INTO CAR_NAMES VALUES(270,'CHEVROLET MONTE CARLO LANDAU', 7, 4);

INSERT INTO CAR_NAMES VALUES(271,'BUICK REGAL SPORT COUPE (TURBO)', 4, 4);

INSERT INTO CAR_NAMES VALUES(272,'FORD FUTURA', 13, 5);

INSERT INTO CAR_NAMES VALUES(273,'DODGE MAGNUM XE', 11, 6);

INSERT INTO CAR_NAMES VALUES(274,'CHEVROLET CHEVETTE', 7, 4);

INSERT INTO CAR_NAMES VALUES(275,'TOYOTA CORONA', 29, 19);

INSERT INTO CAR_NAMES VALUES(276,'DATSUN 510', 10, 8);

INSERT INTO CAR_NAMES VALUES(277,'DODGE OMNI', 11, 6);

INSERT INTO CAR_NAMES VALUES(278,'TOYOTA CELICA GT LIFTBACK', 29, 19);

INSERT INTO CAR_NAMES VALUES(279, 'PLYMOUTH SAPPORO', 24, 6);

INSERT INTO CAR_NAMES VALUES(280,'OLDSMOBILE STARFIRE SX', 21, 4);

INSERT INTO CAR_NAMES VALUES(281,'DATSUN 200-SX', 10, 8);

INSERT INTO CAR_NAMES VALUES(282,'AUDI 5000', 2, 2);

INSERT INTO CAR_NAMES VALUES(283,'VOLVO 264GL', 32, 21);

INSERT INTO CAR_NAMES VALUES(284,'SAAB 99GLE', 27, 17);

INSERT INTO CAR_NAMES VALUES(285,'PEUGEOT 604SL', 23, 15);

INSERT INTO CAR_NAMES VALUES(286,'VOLKSWAGEN SCIROCCO', 31, 2);

INSERT INTO CAR_NAMES VALUES(287,'HONDA ACCORD LX', 15, 11);

INSERT INTO CAR_NAMES VALUES(288,'PONTIAC LEMANS V6', 25, 4);

INSERT INTO CAR_NAMES VALUES(289,'MERCURY ZEPHYR 6', 19, 5);

INSERT INTO CAR_NAMES VALUES(290,'FORD FAIRMONT 4', 13, 5);

INSERT INTO CAR_NAMES VALUES(291,'AMC CONCORD DL 6', 1, 1);

INSERT INTO CAR_NAMES VALUES(292,'DODGE ASPEN 6', 11, 6);

INSERT INTO CAR_NAMES VALUES(293,'CHEVROLET CAPRICE CLASSIC', 7, 4);

INSERT INTO CAR_NAMES VALUES(294,'FORD LTD LANDAU', 13, 5);

INSERT INTO CAR_NAMES VALUES(295,'MERCURY GRAND MARQUIS', 19, 5);

INSERT INTO CAR_NAMES VALUES(296,'DODGE ST. REGIS', 11, 6);

INSERT INTO CAR_NAMES VALUES(297,'BUICK ESTATE WAGON (SW)', 4, 4);

INSERT INTO CAR_NAMES VALUES(298,'FORD COUNTRY SQUIRE (SW)', 13, 5);

INSERT INTO CAR_NAMES VALUES(299,'CHEVROLET MALIBU CLASSIC (SW)', 7, 4);

INSERT INTO CAR_NAMES VALUES(300,'CHRYSLER LEBARON TOWN @ COUNTRY (SW)', 8, 6);

INSERT INTO CAR_NAMES VALUES(301,'VW RABBIT CUSTOM',   31, 2);

INSERT INTO CAR_NAMES VALUES(302, 'MAZDA GLC DELUXE', 16, 12);

INSERT INTO CAR_NAMES VALUES(303,'DODGE COLT HATCHBACK CUSTOM', 11, 6);

INSERT INTO CAR_NAMES VALUES(304,'AMC SPIRIT DL', 1, 1);

INSERT INTO CAR_NAMES VALUES(305,'MERCEDES BENZ 300D', 17, 13);

INSERT INTO CAR_NAMES VALUES(306,'CADILLAC ELDORADO', 5, 4);

INSERT INTO CAR_NAMES VALUES(307,'PEUGEOT 504', 23, 15);

INSERT INTO CAR_NAMES VALUES(308,'OLDSMOBILE CUTLASS SALON BROUGHAM', 21, 4);

INSERT INTO CAR_NAMES VALUES(309,'PLYMOUTH HORIZON', 24, 6);

INSERT INTO CAR_NAMES VALUES(310,'PLYMOUTH HORIZON TC3', 24, 6);

INSERT INTO CAR_NAMES VALUES(311,'DATSUN 210', 10, 8);

INSERT INTO CAR_NAMES VALUES(312,'FIAT STRADA CUSTOM', 12, 9);

INSERT INTO CAR_NAMES VALUES(313,'BUICK SKYLARK LIMITED', 4, 4);

INSERT INTO CAR_NAMES VALUES(314,'CHEVROLET CITATION', 7, 4);

INSERT INTO CAR_NAMES VALUES(315,'OLDSMOBILE OMEGA BROUGHAM', 21, 4);

INSERT INTO CAR_NAMES VALUES(316,'PONTIAC PHOENIX', 25, 4);

INSERT INTO CAR_NAMES VALUES(317,'VW RABBIT', 31, 2);

INSERT INTO CAR_NAMES VALUES(318,'TOYOTA COROLLA TERCEL', 29, 19);

INSERT INTO CAR_NAMES VALUES(319,'CHEVROLET CHEVETTE', 7, 4);

INSERT INTO CAR_NAMES VALUES(320,'DATSUN 310', 10, 8);

INSERT INTO CAR_NAMES VALUES(321,'CHEVROLET CITATION', 7, 4);

INSERT INTO CAR_NAMES VALUES(322,'FORD FAIRMONT', 13, 5);

INSERT INTO CAR_NAMES VALUES(323,'AMC CONCORD', 1, 1);

INSERT INTO CAR_NAMES VALUES(324,'DODGE ASPEN', 11, 6);

INSERT INTO CAR_NAMES VALUES(325,'AUDI 4000', 2, 2);

INSERT INTO CAR_NAMES VALUES(326,'TOYOTA CORONA LIFTBACK', 29, 19);

INSERT INTO CAR_NAMES VALUES(327,'MAZDA 626', 16, 12);

INSERT INTO CAR_NAMES VALUES(328,'DATSUN 510 HATCHBACK', 10, 8);

INSERT INTO CAR_NAMES VALUES(329,'TOYOTA COROLLA', 29, 19);

INSERT INTO CAR_NAMES VALUES(330,'MAZDA GLC', 16, 12);

INSERT INTO CAR_NAMES VALUES(331,'DODGE COLT', 11, 6);

INSERT INTO CAR_NAMES VALUES(332,'DATSUN 210', 10, 8);

INSERT INTO CAR_NAMES VALUES(333,'VW RABBIT C (DIESEL)', 31, 2);

INSERT INTO CAR_NAMES VALUES(334,'VW DASHER (DIESEL)', 31, 2);

INSERT INTO CAR_NAMES VALUES(335,'AUDI 5000S (DIESEL)', 2, 2);

INSERT INTO CAR_NAMES VALUES(336,'MERCEDES-BENZ 240D', 17, 13);

INSERT INTO CAR_NAMES VALUES(337,'HONDA CIVIC 1500 GL', 15, 11);

INSERT INTO CAR_NAMES VALUES(338,'RENAULT LECAR DELUXE', 26, 16);

INSERT INTO CAR_NAMES VALUES(339,'SUBARU DL', 28, 18);

INSERT INTO CAR_NAMES VALUES(340, 'VOLKSWAGEN RABBIT', 31, 2);

INSERT INTO CAR_NAMES VALUES(341,'DATSUN 280-ZX', 10, 8);

INSERT INTO CAR_NAMES VALUES(342,'MAZDA RX-7 GS', 16, 12);

INSERT INTO CAR_NAMES VALUES(343,'TRIUMPH TR7 COUPE', 30, 20);

INSERT INTO CAR_NAMES VALUES(344,'FORD MUSTANG COBRA', 13, 5);

INSERT INTO CAR_NAMES VALUES(345,'HONDA ACCORD', 15, 11);

INSERT INTO CAR_NAMES VALUES(346,'PLYMOUTH RELIANT', 24, 6);

INSERT INTO CAR_NAMES VALUES(347,'BUICK SKYLARK', 4, 4);

INSERT INTO CAR_NAMES VALUES(348,'DODGE ARIES WAGON (SW)', 11, 6);

INSERT INTO CAR_NAMES VALUES(349,'CHEVROLET CITATION', 7, 4);

INSERT INTO CAR_NAMES VALUES(350,'PLYMOUTH RELIANT', 24, 6);

INSERT INTO CAR_NAMES VALUES(351,'TOYOTA STARLET', 29, 19);

INSERT INTO CAR_NAMES VALUES(352,'PLYMOUTH CHAMP', 24, 6);

INSERT INTO CAR_NAMES VALUES(353,'HONDA CIVIC 1300', 15, 11);

INSERT INTO CAR_NAMES VALUES(354,'SUBARU', 28, 18);  

INSERT INTO CAR_NAMES VALUES(355,'DATSUN 210 MPG', 10, 8);

INSERT INTO CAR_NAMES VALUES(356,'TOYOTA TERCEL', 29, 19);

INSERT INTO CAR_NAMES VALUES(357,'MAZDA GLC 4', 16, 12);

INSERT INTO CAR_NAMES VALUES(358,'PLYMOUTH HORIZON 4', 24, 6);

INSERT INTO CAR_NAMES VALUES(359,'FORD ESCORT 4W', 13, 5);

INSERT INTO CAR_NAMES VALUES(360,'FORD ESCORT 2H', 13, 5);

INSERT INTO CAR_NAMES VALUES(361, 'VOLKSWAGEN JETTA', 31, 2);

INSERT INTO CAR_NAMES VALUES(362,'RENAULT 18I', 26, 16);

INSERT INTO CAR_NAMES VALUES(363,'HONDA PRELUDE', 15, 11);

INSERT INTO CAR_NAMES VALUES(364,'TOYOTA COROLLA', 29, 19);

INSERT INTO CAR_NAMES VALUES(365,'DATSUN 200SX', 10, 8);

INSERT INTO CAR_NAMES VALUES(366,'MAZDA 626', 16, 12);

INSERT INTO CAR_NAMES VALUES(367,'PEUGEOT 505S TURBO DIESEL', 23, 15);

INSERT INTO CAR_NAMES VALUES(368,'SAAB 900S', 27, 17);

INSERT INTO CAR_NAMES VALUES(369,'VOLVO DIESEL', 32, 21);

INSERT INTO CAR_NAMES VALUES(370,'TOYOTA CRESSIDA', 29, 19);

INSERT INTO CAR_NAMES VALUES(371,'DATSUN 810 MAXIMA', 10, 8);

INSERT INTO CAR_NAMES VALUES(372,'BUICK CENTURY', 4, 4);

INSERT INTO CAR_NAMES VALUES(373,'OLDSMOBILE CUTLASS LS', 21, 4);

INSERT INTO CAR_NAMES VALUES(374,'FORD GRANADA GL', 13, 5);

INSERT INTO CAR_NAMES VALUES(375,'CHRYSLER LEBARON SALON', 8, 6);

INSERT INTO CAR_NAMES VALUES(376,'CHEVROLET CAVALIER', 7, 4);

INSERT INTO CAR_NAMES VALUES(377,'CHEVROLET CAVALIER WAGON', 7, 4);

INSERT INTO CAR_NAMES VALUES(378,'CHEVROLET CAVALIER 2-DOOR', 7, 4);

INSERT INTO CAR_NAMES VALUES(379,'PONTIAC J2000 SE HATCHBACK', 25, 4);

INSERT INTO CAR_NAMES VALUES(380,'DODGE ARIES SE', 11, 6);

INSERT INTO CAR_NAMES VALUES(381,'PONTIAC PHOENIX', 25, 4);

INSERT INTO CAR_NAMES VALUES(382,'FORD FAIRMONT FUTURA', 13, 5);

INSERT INTO CAR_NAMES VALUES(383,'AMC CONCORD DL', 1, 1);

INSERT INTO CAR_NAMES VALUES(384,'VOLKSWAGEN RABBIT L', 31, 2);

INSERT INTO CAR_NAMES VALUES(385,'MAZDA GLC CUSTOM L', 16, 12);

INSERT INTO CAR_NAMES VALUES(386,'MAZDA GLC CUSTOM', 16, 12);

INSERT INTO CAR_NAMES VALUES(387,'PLYMOUTH HORIZON MISER', 24, 6);

INSERT INTO CAR_NAMES VALUES(388,'MERCURY LYNX L', 19, 5);

INSERT INTO CAR_NAMES VALUES(389,'NISSAN STANZA XE', 10, 8);

INSERT INTO CAR_NAMES VALUES(390,'HONDA ACCORD', 15, 11);

INSERT INTO CAR_NAMES VALUES(391,'TOYOTA COROLLA', 29, 19);

INSERT INTO CAR_NAMES VALUES(392,'HONDA CIVIC', 15, 11);

INSERT INTO CAR_NAMES VALUES(393,'HONDA CIVIC (AUTO)', 15, 11);

INSERT INTO CAR_NAMES VALUES(394,'DATSUN 310 GX', 10, 8);

INSERT INTO CAR_NAMES VALUES(395,'BUICK CENTURY LIMITED', 4, 4);

INSERT INTO CAR_NAMES VALUES(396,'OLDSMOBILE CUTLASS CIERA (DIESEL)', 21, 4);

INSERT INTO CAR_NAMES VALUES(397,'CHRYSLER LEBARON MEDALLION', 8, 6);

INSERT INTO CAR_NAMES VALUES(398,'FORD GRANADA L', 13, 5);

INSERT INTO CAR_NAMES VALUES(399,'TOYOTA CELICA GT', 29, 19);

INSERT INTO CAR_NAMES VALUES(400, 'DODGE CHARGER 2.2', 11, 6);

INSERT INTO CAR_NAMES VALUES(401,'CHEVROLET CAMARO', 7, 4);

INSERT INTO CAR_NAMES VALUES(402,'FORD MUSTANG GL', 13, 5);

INSERT INTO CAR_NAMES VALUES(403,'VW PICKUP', 31, 2);

INSERT INTO CAR_NAMES VALUES(404,'DODGE RAMPAGE', 11, 6);

INSERT INTO CAR_NAMES VALUES(405,'FORD RANGER', 13, 5);

INSERT INTO CAR_NAMES VALUES(406,'CHEVY S-10', 7, 4);