Subscriber Broker affiliation
CREATE TABLE HC.SUBSCRIBER_BROKER
(
    SUBSCRIBER_KEY NUMBER, subscriber key
    SUBSCRIBER_BROKER_ID VARCHAR2 (9), broker license id
    SUBSCRIBER_BROKER_EFFECTIVE_DATE TIMESTAMP broker license effective date
);

CREATE TABLE HC.SUBSCRIBER 
(
    SUBSCRIBER_ID VARCHAR2(9),
    SUBSCRIBER_KEY NUMBER CONSTRAINT U_CONS_SUB UNIQUE,
    SUBSCRIBER_FIRST_NAME VARCHAR2 (40),
    SUBSCRIBER_LAST_NAME VARCHAR2 (40)
);
--
INSERT INTO HC.SUBSCRIBER (SUBSCRIBER_ID, SUBSCRIBER_KEY, SUBSCRIBER_FIRST_NAME, SUBSCRIBER_LAST_NAME) 
VALUES ('SUB001', 101, 'John', 'Doe');

INSERT INTO HC.SUBSCRIBER (SUBSCRIBER_ID, SUBSCRIBER_KEY, SUBSCRIBER_FIRST_NAME, SUBSCRIBER_LAST_NAME) 
VALUES ('SUB002', 102, 'Alice', 'Smith');

INSERT INTO HC.SUBSCRIBER (SUBSCRIBER_ID, SUBSCRIBER_KEY, SUBSCRIBER_FIRST_NAME, SUBSCRIBER_LAST_NAME) 
VALUES ('SUB003', 103, 'Michael', 'Brown');

INSERT INTO HC.SUBSCRIBER (SUBSCRIBER_ID, SUBSCRIBER_KEY, SUBSCRIBER_FIRST_NAME, SUBSCRIBER_LAST_NAME) 
VALUES ('SUB004', 104, 'Emma', 'Johnson');
--
COMMIT;
--
Broker information
CREATE TABLE HC.BROKER 
(
    BROKER_ID VARCHAR2(12), broker id
    COMMON_BROKER_ID VARCHAR2(12), common broker id
    BROKER_KEY NUMBER CONSTRAINT U_CONS_BROKER UNIQUE, broker key
    BROKER_NAME VARCHAR2 (40) broker name
    
);
--
INSERT INTO HC.BROKER (BROKER_ID, COMMON_BROKER_ID, BROKER_KEY, BROKER_NAME) 
VALUES ('BROKER001', 'COMBROKER01', 201, 'Alpha Investments');

INSERT INTO HC.BROKER (BROKER_ID, COMMON_BROKER_ID, BROKER_KEY, BROKER_NAME) 
VALUES ('BROKER002', 'COMBROKER02', 202, 'Beta Securities');

INSERT INTO HC.BROKER (BROKER_ID, COMMON_BROKER_ID, BROKER_KEY, BROKER_NAME) 
VALUES ('BROKER003', 'COMBROKER03', 203, 'Gamma Traders');

INSERT INTO HC.BROKER (BROKER_ID, COMMON_BROKER_ID, BROKER_KEY, BROKER_NAME) 
VALUES ('BROKER004', 'COMBROKER04', 204, 'Delta Financials');
--
COMMIT;
--
CREATE TABLE HC.COMMON_BROKER 
(
    COMMON_BROKER_ID VARCHAR2(12),
    COMMON_BROKER_NAME VARCHAR2 (40)
);
--
INSERT INTO HC.COMMON_BROKER (COMMON_BROKER_ID, COMMON_BROKER_NAME) 
VALUES ('COMBROKER01', 'Global Investments');

INSERT INTO HC.COMMON_BROKER (COMMON_BROKER_ID, COMMON_BROKER_NAME) 
VALUES ('COMBROKER02', 'Prime Securities');

INSERT INTO HC.COMMON_BROKER (COMMON_BROKER_ID, COMMON_BROKER_NAME) 
VALUES ('COMBROKER03', 'Elite Brokerage');

INSERT INTO HC.COMMON_BROKER (COMMON_BROKER_ID, COMMON_BROKER_NAME) 
VALUES ('COMBROKER04', 'Summit Finance');
--
COMMIT;
--
Broker Lincese
CREATE TABLE HC.BROKER_LICENSE
(
    BROKER_LICENSE_ID VARCHAR2(9), broker license id
    COMMON_BROKER_ID VARCHAR2(12), common broker id
    LICENSE_EFFECTIVE_DATE TIMESTAMP, broker license effective date
    LICENSE_TERM_DATE TIMESTAMP broker license termination date
);
--
INSERT INTO HC.BROKER_LICENSE (BROKER_LICENSE_ID, COMMON_BROKER_ID, LICENSE_EFFECTIVE_DATE, LICENSE_TERM_DATE) 
VALUES ('LIC001', 'COMBROKER01', TO_TIMESTAMP('2023-01-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-01-01 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HC.BROKER_LICENSE (BROKER_LICENSE_ID, COMMON_BROKER_ID, LICENSE_EFFECTIVE_DATE, LICENSE_TERM_DATE) 
VALUES ('LIC002', 'COMBROKER02', TO_TIMESTAMP('2022-06-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-06-15 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HC.BROKER_LICENSE (BROKER_LICENSE_ID, COMMON_BROKER_ID, LICENSE_EFFECTIVE_DATE, LICENSE_TERM_DATE) 
VALUES ('LIC003', 'COMBROKER03', TO_TIMESTAMP('2024-03-10 08:45:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-03-10 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HC.BROKER_LICENSE (BROKER_LICENSE_ID, COMMON_BROKER_ID, LICENSE_EFFECTIVE_DATE, LICENSE_TERM_DATE) 
VALUES ('LIC004', 'COMBROKER04', TO_TIMESTAMP('2021-12-01 07:15:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-12-01 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
--
--
CREATE TABLE HC.COMMISION_STATEMENT
(
    ARRANGEMENT_ID VARCHAR2 (12),
    BROKER_ID VARCHAR2(12),
    BROKER_NAME VARCHAR2 (40),
    INVOICE_DUE_DATE DATE,
    COMMISION_PAYMENT_DATE DATE,
    COMMISION_NET_CHECK_AMOUNT NUMBER,
    LINE_OF_BUSINESS_ID VARCHAR2(4)
);
--
INSERT INTO HC.COMMISION_STATEMENT 
(ARRANGEMENT_ID, BROKER_ID, BROKER_NAME, INVOICE_DUE_DATE, COMMISION_PAYMENT_DATE, COMMISION_NET_CHECK_AMOUNT, LINE_OF_BUSINESS_ID) 
VALUES 
('ARR001', 'BROKER001', 'Alpha Investments', 
 TO_TIMESTAMP('2024-02-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
 TO_TIMESTAMP('2024-02-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
 5000.00, 'LOB1');

INSERT INTO HC.COMMISION_STATEMENT 
(ARRANGEMENT_ID, BROKER_ID, BROKER_NAME, INVOICE_DUE_DATE, COMMISION_PAYMENT_DATE, COMMISION_NET_CHECK_AMOUNT, LINE_OF_BUSINESS_ID) 
VALUES 
('ARR002', 'BROKER002', 'Beta Securities', 
 TO_TIMESTAMP('2024-01-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
 TO_TIMESTAMP('2024-01-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
 7500.50, 'LOB2');

INSERT INTO HC.COMMISION_STATEMENT 
(ARRANGEMENT_ID, BROKER_ID, BROKER_NAME, INVOICE_DUE_DATE, COMMISION_PAYMENT_DATE, COMMISION_NET_CHECK_AMOUNT, LINE_OF_BUSINESS_ID) 
VALUES 
('ARR003', 'BROKER003', 'Gamma Traders', 
 TO_TIMESTAMP('2023-12-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
 TO_TIMESTAMP('2023-12-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
 6200.75, 'LOB3');

INSERT INTO HC.COMMISION_STATEMENT 
(ARRANGEMENT_ID, BROKER_ID, BROKER_NAME, INVOICE_DUE_DATE, COMMISION_PAYMENT_DATE, COMMISION_NET_CHECK_AMOUNT, LINE_OF_BUSINESS_ID) 
VALUES 
('ARR004', 'BROKER004', 'Delta Financials', 
 TO_TIMESTAMP('2024-03-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
 TO_TIMESTAMP('2024-03-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
 8300.25, 'LOB4');
--
COMMIT;