DROP USER cit225 CASCADE;

CREATE USER cit225
  IDENTIFIED BY oracle
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;


ALTER USER cit225 QUOTA UNLIMITED ON USERS;