DROP USER ora_demo CASCADE;
--
CREATE USER ora_demo IDENTIFIED BY oracle
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
PROFILE default
ACCOUNT UNLOCK;
--
ALTER USER ora_demo QUOTA UNLIMITED ON users;
--
CREATE TABLE ora_demo.emp AS SELECT * FROM emp;
--
CREATE TABLE ora_demo.dept AS SELECT * FROM dept;