SET LINESIZE 180
col B_ID format 999
col B_NAME format a20
col START_ID format 9999
col START_SNAP_TIME format a20
col END_ID format 9999
col END_SNAP_TIME format a20
col EXP format 999
SELECT BASELINE_ID B_ID, BASELINE_NAME B_NAME, START_SNAP_ID START_ID, 
       TO_CHAR(START_SNAP_TIME, 'DD-MON-YYYY HH24:MI') AS START_SNAP_TIME, END_SNAP_ID END_ID,
       TO_CHAR(END_SNAP_TIME, 'DD-MON-YYYY HH24:MI') AS END_SNAP_TIME,
EXPIRATION EXP, BASELINE_TYPE 
FROM   DBA_HIST_BASELINE
ORDER BY BASELINE_ID;

