col SID format 999999
col USERNAME format a10
col DBTIME format 9999999999999
col WAITTIME format 9999999999999
col WAITPCT format 99999.99
col ONCPUPCT format 99999.99
SELECT M.SID, S.USERNAME
           ,VALUE DBTIME
           ,WAITTIME WAITTIME
           ,ROUND((WAITTIME/VALUE)*100,2) WAITPCT
           ,ROUND(((VALUE-WAITTIME)/VALUE)*100,2) ONCPU_PCT
      FROM(SELECT SID, STAT_ID, STAT_NAME ,VALUE
            ,VALUE - (LEAD(VALUE,1) OVER(PARTITION BY SID ORDER BY SID,STAT_NAME DESC)) WAITTIME
           FROM GV$SESS_TIME_MODEL
           WHERE STAT_NAME IN ('DB time','DB CPU')) M,
		   GV$SESSION S
WHERE M.SID = S.SID
      AND STAT_NAME='DB time' AND WAITTIME>0
ORDER BY WAITPCT DESC;
