set linesize 180
set pagesize 30
col INFO format a80
SELECT
'TEMPLATE_ID: ' ||TEMPLATE_ID || CHR(10) ||
'TEMPLATE_NAME: ' ||TEMPLATE_NAME || CHR(10) ||
'TEMPLATE_TYPE: ' ||TEMPLATE_TYPE || CHR(10) ||
'BASELINE_NAME_PREFIX: ' ||BASELINE_NAME_PREFIX || CHR(10) ||
'START_TIME: ' ||TO_CHAR(START_TIME,'DD-MM-RR HH24:MI:SS') || CHR(10) ||
'END_TIME: ' || TO_CHAR(END_TIME,'DD-MM-RR HH24:MI:SS') || CHR(10) ||
'DAY_OF_WEEK: ' ||DAY_OF_WEEK || CHR(10) ||
'HOUR_IN_DAY: ' ||HOUR_IN_DAY || CHR(10) ||
'DURATION: ' ||DURATION || CHR(10) ||
'EXPIRATION: ' ||EXPIRATION || CHR(10) ||
'REPEAT_INTERVAL: ' ||REPEAT_INTERVAL || CHR(10) ||
'LAST_GENERATED: ' ||TO_CHAR(LAST_GENERATED,'DD-MM-RR HH24:MI:SS') as INFO
FROM DBA_HIST_BASELINE_TEMPLATE
ORDER BY TEMPLATE_ID;
