-- list AWR snapshots captured today
col BEGIN_INTERVAL_TIME format a28
col END_INTERVAL_TIME format a28

SELECT SNAP_ID, BEGIN_INTERVAL_TIME, END_INTERVAL_TIME
  FROM DBA_HIST_SNAPSHOT
WHERE TRUNC(BEGIN_INTERVAL_TIME) = TRUNC(SYSDATE)
ORDER BY SNAP_ID;
--