begin
 DBMS_SESSION.SET_IDENTIFIER('Top Customers Report');
 INSERT /*+ APPEND */ INTO ORDERS2 SELECT S.NEXTVAL, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL FROM ORDERS WHERE ORDER_ID <=50000;
 COMMIT;
end;
/


