-- name collections.sql
-- To demonstrate all types of collections in Oracle PL/SQL
--
-- Recap: Different kinds of SQL and PL/SQL composite data types
-- 
-- SQL user-defined datatype (UDT): This can hold a data structure. Two implementations
-- are possible: an object type only implementation, which supports a SQL-level record structure,
-- and both an object type and body implementation, which supports a class instance.
-- SQL UDTs are defined at schema level. 
--
-- PL/SQL record type: This holds a strcuture of data. You can implement it by anchoring 
-- the data type of elements to columns in tables and views, or you can explicitly define it. 
-- Record types are defined in PL/SQL blocks.
--
-- SQL Collection: This can hold a list of any scalar SQL data type. SQL collections of
-- scalar variables are called Attribute Data Types (ADTs). 
-- 
-- There are two kinds of SQL collections:
-- 
-- Varray which is a fixed length array and nested table. 
-- 
-- Nested table doesn’t have a fixed number of elements at definition and can scale to meet
-- your runtime needs within your PGA memory constraints. 
-- 
-- SQL collections are defined at schema or PL/SQL blocks.
--
-- PL/SQL Collection: This can hold a list of any scalar SQL data type or record type, and it
-- can also hold a list of any PL/SQL record type. PL/SQL collections are implemented using 
-- associative array and defined only at PL/SQL blocks.
--
