-- retrieve data from TM_HISTORY
set linesize 180
SELECT
    TO_CHAR(DBTIME, '999,999,999')  DBTIME,
    TO_CHAR(DBCPU, '999,999,999')    DBCPU,
    ROUND(DBCPU - LAG(DBCPU, 1, 0) OVER (ORDER BY DBCPU)) AS DBCPU_DIFF,
    TO_CHAR(WAIT_TIME,'999,999,999,999')  WAIT_TIME,
    ROUND(WAIT_TIME - LAG(WAIT_TIME,1,0) OVER (ORDER BY WAIT_TIME)) AS WAIT_TIME_DIFF,
    TO_CHAR((DBTIME-DBCPU)/DBTIME*100, '99.99') || '%' WAIT_PCT,
    USERS_CNT,
    ROUND((DBTIME-DBCPU)/USERS_CNT) WAIT_USER_SHARE
FROM
    TM_HISTORY
ORDER BY
    SNAP_ID;